### ISSUE TITLE
A question with your 4D conv implementation

### ISSUE THREAD

**Issue by anilrgukt** [mhuen/TFScripts#2]
I am a bit new to TF and I need a 4D convolution for my applications. I want to make sure if your 4D conv is exact and doesn't involve any kernel factorization or approximation assumptions. 

Thanks,
Anil

**Comment by anilrgukt** [comment]
Answer was there in earlier closed issue. Thanks.

**Comment by mhuen** [comment]
Let me know if you have any further questions.
