### ISSUE TITLE
4D transpose convolutional layer

### ISSUE THREAD

**Issue by OrodRazeghi** [mhuen/TFScripts#4]
Thank you for sharing a nice implementation of a 4D conv layer in tensorflow. I was wondering if you have the transpose version of the implemented 4D layer or you could kindly describe to me how the implementation of the transpose would look like. Any comments will be very appreciated, thanks.

**Comment by mhuen** [comment]
Unfortunately I have not looked into this yet. Maybe a starting point would be to look at how the tensorflow implementation generalizes from tf.nn.conv1d_transpose to tf.nn.conv2d_transpose  and tf.nn.conv3d_transpose. Sorry that I can't be of more help

**Comment by OrodRazeghi** [comment]
Thank you for your reply, I will look into this.
